# Generated by Django 4.2.19 on 2025-02-28 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountholder',
            name='balance',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='accountholder',
            name='ifsc',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='user',
            name='account',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='banking.accountholder'),
        ),
    ]
