# Generated by Django 4.2.19 on 2025-02-28 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0002_alter_accountholder_balance_alter_accountholder_ifsc_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loanapplication',
            old_name='amount',
            new_name='annual_income',
        ),
        migrations.RemoveField(
            model_name='creditcardapplication',
            name='documents',
        ),
        migrations.RemoveField(
            model_name='loanapplication',
            name='documents',
        ),
        migrations.AddField(
            model_name='creditcardapplication',
            name='annual_income',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='creditcardapplication',
            name='card_type',
            field=models.CharField(choices=[('platinum', 'Platinum Card'), ('gold', 'Gold Card'), ('silver', 'Silver Card')], default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='creditcardapplication',
            name='cibil_score',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='creditcardapplication',
            name='employment_status',
            field=models.CharField(choices=[('salaried', 'Salaried'), ('self-employed', 'Self-Employed'), ('unemployed', 'Unemployed')], default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='creditcardapplication',
            name='id_proof',
            field=models.FileField(default=1, upload_to='documents/id_proofs/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='creditcardapplication',
            name='purpose',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='creditcardapplication',
            name='salary_slip',
            field=models.FileField(blank=True, null=True, upload_to='documents/salary_slips/'),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='cibil_score',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='employment_status',
            field=models.CharField(choices=[('salaried', 'Salaried'), ('self-employed', 'Self-Employed'), ('unemployed', 'Unemployed')], default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='id_proof',
            field=models.FileField(default=1, upload_to='documents/id_proofs/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='loan_amount',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='loan_type',
            field=models.CharField(choices=[('home', 'Home Loan'), ('personal', 'Personal Loan'), ('car', 'Car Loan'), ('education', 'Education Loan')], default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='possession_certificate',
            field=models.FileField(default=1, upload_to='documents/possession_certificates/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='purpose',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='salary_slip',
            field=models.FileField(blank=True, null=True, upload_to='documents/salary_slips/'),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='tenure',
            field=models.IntegerField(default=1, help_text='Loan tenure in years'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='written_request',
            field=models.FileField(default=1, upload_to='documents/written_requests/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='creditcardapplication',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
