# Generated by Django 4.2.19 on 2025-02-28 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0003_rename_amount_loanapplication_annual_income_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='creditcardapplication',
            old_name='applied_on',
            new_name='applied_date',
        ),
        migrations.RenameField(
            model_name='loanapplication',
            old_name='applied_on',
            new_name='applied_date',
        ),
        migrations.RenameField(
            model_name='loanapplication',
            old_name='purpose',
            new_name='loan_purpose',
        ),
        migrations.RemoveField(
            model_name='creditcardapplication',
            name='card_type',
        ),
        migrations.RemoveField(
            model_name='creditcardapplication',
            name='purpose',
        ),
        migrations.RemoveField(
            model_name='loanapplication',
            name='annual_income',
        ),
        migrations.RemoveField(
            model_name='loanapplication',
            name='cibil_score',
        ),
        migrations.RemoveField(
            model_name='loanapplication',
            name='employment_status',
        ),
        migrations.RemoveField(
            model_name='loanapplication',
            name='loan_type',
        ),
        migrations.RemoveField(
            model_name='loanapplication',
            name='tenure',
        ),
        migrations.AddField(
            model_name='creditcardapplication',
            name='address_proof',
            field=models.FileField(default=1, upload_to='documents/address_proofs/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='creditcardapplication',
            name='email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='creditcardapplication',
            name='full_name',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='creditcardapplication',
            name='phone_number',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='employment_type',
            field=models.CharField(choices=[('Salaried', 'Salaried'), ('Self-Employed', 'Self-Employed')], default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='existing_loans',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='full_name',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='loan_duration',
            field=models.IntegerField(default=1, help_text='Duration in months'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='monthly_income',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='phone_number',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='creditcardapplication',
            name='employment_status',
            field=models.CharField(choices=[('Salaried', 'Salaried'), ('Self-Employed', 'Self-Employed')], max_length=100),
        ),
        migrations.AlterField(
            model_name='creditcardapplication',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='possession_certificate',
            field=models.FileField(blank=True, null=True, upload_to='documents/possession_certificates/'),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
    ]
