# Generated by Django 4.2.19 on 2025-03-02 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0005_loandisbursement_loaninstallment'),
    ]

    operations = [
        migrations.AddField(
            model_name='loaninstallment',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('initiated', 'Payment Initiated'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='loaninstallment',
            name='razorpay_order_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='loaninstallment',
            name='razorpay_payment_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='loaninstallment',
            name='razorpay_signature',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
