# Generated by Django 4.2.19 on 2025-03-02 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0006_loaninstallment_payment_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loaninstallment',
            old_name='razorpay_order_id',
            new_name='order_id',
        ),
        migrations.RenameField(
            model_name='loaninstallment',
            old_name='razorpay_payment_id',
            new_name='payment_id',
        ),
        migrations.RemoveField(
            model_name='loaninstallment',
            name='payment_status',
        ),
        migrations.RemoveField(
            model_name='loaninstallment',
            name='razorpay_signature',
        ),
        migrations.AddField(
            model_name='loaninstallment',
            name='payment_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
