# Generated by Django 4.2.19 on 2025-03-02 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0007_rename_razorpay_order_id_loaninstallment_order_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditCardDisbursement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disbursement_date', models.DateField(auto_now_add=True)),
                ('credit_limit', models.DecimalField(decimal_places=2, max_digits=12)),
                ('annual_fee', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('interest_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('card_number', models.CharField(blank=True, max_length=16, null=True)),
                ('expiry_date', models.DateField()),
                ('credit_card_application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='disbursement', to='banking.creditcardapplication')),
            ],
        ),
        migrations.CreateModel(
            name='CreditCardBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_date', models.DateField()),
                ('due_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('minimum_payment', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid'), ('Overdue', 'Overdue')], default='Pending', max_length=20)),
                ('payment_id', models.CharField(blank=True, max_length=100, null=True)),
                ('order_id', models.CharField(blank=True, max_length=100, null=True)),
                ('payment_date', models.DateTimeField(blank=True, null=True)),
                ('disbursement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bills', to='banking.creditcarddisbursement')),
            ],
        ),
    ]
