# Generated by Django 4.2.19 on 2025-03-02 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0008_creditcarddisbursement_creditcardbill'),
    ]

    operations = [
        migrations.RenameField(
            model_name='creditcarddisbursement',
            old_name='credit_card_application',
            new_name='card_application',
        ),
        migrations.RemoveField(
            model_name='creditcardbill',
            name='minimum_payment',
        ),
        migrations.RemoveField(
            model_name='creditcarddisbursement',
            name='card_number',
        ),
        migrations.RemoveField(
            model_name='creditcarddisbursement',
            name='expiry_date',
        ),
    ]
