# Generated by Django 4.2.19 on 2025-03-02 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0010_rename_card_application_creditcarddisbursement_credit_card_application_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CreditCardDisbursement',
        ),
    ]
